import { useState } from "react";
import { ArrowRight, CalendarDays, CheckSquare2, FileText, FolderKanban, Mic, Search, Upload, AlertCircle } from "lucide-react";
import type { ActionItem, Decision, Meeting, Project, View } from "./types";
interface Props { projects:Project[]; meetings:Meeting[]; actions:ActionItem[]; decisions:Decision[]; userName:string; onNavigate:(view:View)=>void; onNewMeeting:()=>void; onOpenProject:(id:number)=>void; onOpenMeeting:(id:number)=>void; onOpenAction:(id:number)=>void; onOpenDecision:(id:number)=>void; }
const labels:Record<string,string>={todo:"할 일",in_progress:"진행 중",done:"완료",cancelled:"취소",draft:"검토 대기",confirmed:"확정"};
const dayKey=(date:Date)=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul"}).format(date);
export default function HomeDashboard(p:Props) {
 const [filter,setFilter]=useState(""); const [query,setQuery]=useState("");
 const today=dayKey(new Date()); const local=new Date(`${today}T00:00:00`); const start=new Date(local); start.setDate(local.getDate()-(local.getDay()+6)%7); const end=new Date(start);end.setDate(start.getDate()+7);
 const localKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
 const open=p.actions.filter(a=>!["done","cancelled"].includes(a.status));
 const week=p.meetings.filter(m=>m.meeting_date.slice(0,10)>=localKey(start)&&m.meeting_date.slice(0,10)<localKey(end));
 const mine=p.actions.filter(a=>a.assignee===p.userName);const personal=mine.length>0;
 const source=personal?mine:p.actions;
 const match=(text:string)=>text.toLowerCase().includes(query.trim().toLowerCase());
 const meetings=[...p.meetings].filter(m=>match(m.title)).sort((a,b)=>b.meeting_date.localeCompare(a.meeting_date)).slice(0,3);
 const actions=source.filter(a=>(!filter||a.status===filter)&&match(a.task)).sort((a,b)=>(a.due_date||"9999").localeCompare(b.due_date||"9999")).slice(0,4);
 const decisions=[...p.decisions].filter(d=>match(d.topic)).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,3);
 const projectName=(id:number)=>p.projects.find(x=>x.id===id)?.name||"프로젝트";
 const heading=(title:string,view:View)=><header className="home-panel-head"><h2>{title}</h2><button onClick={()=>p.onNavigate(view)}>전체보기<ArrowRight/></button></header>;
 const empty=(text:string)=><div className="home-empty">{text}</div>;
 return <div className="page home-page"><section className="home-welcome"><div><span className="home-eyebrow">YOUR TEAM, IN FLOW</span><h2>안녕하세요, {p.userName}님! <span>👋</span></h2><p>회의의 결정을 팀의 실행으로 이어가세요.</p></div><time>{new Intl.DateTimeFormat("ko-KR",{dateStyle:"full",timeZone:"Asia/Seoul"}).format(new Date())}</time></section>
 <label className="home-search"><Search/><input type="search" placeholder="홈의 프로젝트, 회의, 업무, 결정 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <div className="metric-grid home-metrics">{[{label:"진행 중 업무",value:open.length,icon:CheckSquare2,tone:"blue",view:"actions"},{label:"오늘 마감",value:open.filter(a=>a.due_date?.slice(0,10)===today).length,icon:AlertCircle,tone:"rose",view:"actions"},{label:"이번 주 회의",value:week.length,icon:CalendarDays,tone:"mint",view:"meetings"},{label:"검토 대기 결정",value:p.decisions.filter(d=>d.status==="draft").length,icon:FileText,tone:"purple",view:"decisions"}].map(m=><button className={`metric home-metric ${m.tone}`} key={m.label} onClick={()=>p.onNavigate(m.view as View)}><span className="metric-icon"><m.icon/></span><div><span>{m.label}</span><strong>{m.value}</strong></div></button>)}</div>
 <section className="meeting-shortcut"><div><span className="metric-icon purple"><Mic/></span><div><b>새로운 회의를 시작해 볼까요?</b><p>녹음하거나 파일을 올리고, AI로 요약과 결정을 정리하세요.</p></div></div><button className="button primary" onClick={p.onNewMeeting}><Upload/>회의 등록 · 녹음</button></section>
 <div className="home-grid"><section className="panel">{heading("최근 회의","meetings")}<div className="home-records">{meetings.length?meetings.map(m=><button className="home-record" key={m.id} onClick={()=>p.onOpenMeeting(m.id)}><span className="record-icon"><FileText/></span><div><b>{m.title}</b><small>{m.meeting_date.slice(0,10)} · {m.participants.length}명 참석</small><span className="project-chip">{projectName(m.project_id)}</span></div><span className="record-tail">회의록 보기<ArrowRight/></span></button>):empty("회의가 없습니다. 첫 회의를 등록해 보세요.")}</div></section>
 <section className="panel">{heading(personal?"내 업무":"팀 업무","actions")}<div className="home-tabs" role="group" aria-label="업무 상태">{[["","전체"],["in_progress","진행 중"],["todo","할 일"],["done","완료"]].map(([key,label])=><button aria-pressed={filter===key} className={filter===key?"active":""} key={key} onClick={()=>setFilter(key)}>{label} ({source.filter(a=>!key||a.status===key).length})</button>)}</div>{actions.length?actions.map(a=><button className="home-task" key={a.id} onClick={()=>p.onOpenAction(a.id)}><span className={`task-dot ${a.status}`}/><div><small>#{a.id} · {a.assignee||"담당자 미지정"}</small><b>{a.task}</b><small className="task-due">{a.due_date?`마감 ${a.due_date.slice(0,10)}`:"기한 미정"}</small></div><span className={`badge ${a.status}`}>{labels[a.status]||a.status}</span></button>):empty("해당하는 업무가 없습니다.")}</section>
 <section className="panel">{heading("프로젝트 현황","projects")}<div className="home-projects">{p.projects.filter(x=>match(x.name)).slice(0,3).map((project,index)=>{const tasks=p.actions.filter(a=>a.project_id===project.id&&a.status!=="cancelled");const done=tasks.filter(a=>a.status==="done").length;const progress=tasks.length?Math.round(done/tasks.length*100):0;return <button className={`home-project tone-${index}`} key={project.id} onClick={()=>p.onOpenProject(project.id)}><span className="record-icon"><FolderKanban/></span><b>{project.name}</b><small>{project.description||"프로젝트 업무 공간"}</small><div className="home-progress"><span style={{width:`${progress}%`}}/></div><small>업무 완료율 {progress}%</small><footer><span>회의 <b>{p.meetings.filter(m=>m.project_id===project.id).length}</b></span><span>업무 <b>{tasks.length}</b></span><span>결정 <b>{p.decisions.filter(d=>d.project_id===project.id).length}</b></span></footer></button>})}{!p.projects.length&&empty("프로젝트를 만들고 팀의 업무를 모아보세요.")}</div></section>
 <section className="panel">{heading("최근 결정사항","decisions")}{decisions.length?decisions.map(d=><button className="home-task" key={d.id} onClick={()=>p.onOpenDecision(d.id)}><span className="record-icon"><FileText/></span><div><b>{d.topic}</b><small>{projectName(d.project_id)} · {d.updated_at.slice(0,10)}</small></div><span className={`badge ${d.status}`}>{labels[d.status]||d.status}</span></button>):empty("등록된 결정사항이 없습니다.")}</section></div>
 </div>;
}
