export interface CandidateDraft {
 decisions?:{topic:string;value:string;evidence?:string}[];
 action_items?:{task:string;assignee?:string|null;due_date?:string|null;priority?:string;evidence?:string}[];
 follow_up_topics?:string[];
 speaker_segments?:unknown[];
}

export default function MeetingCandidates({value,onChange,disabled,onChooseTask,onConfirmDecisions}:{value:CandidateDraft;onChange:(value:CandidateDraft)=>void;disabled:boolean;onChooseTask?:(task:string,date:string)=>void;onConfirmDecisions?:()=>void}) {
 return <section><h3>결정 후보</h3>{(value.decisions||[]).map((d,i)=><article className="workflow-entry" key={i}><label>결정 주제<input disabled={disabled} value={d.topic} onChange={e=>onChange({...value,decisions:value.decisions!.map((v,j)=>j===i?{...v,topic:e.target.value}:v)})}/></label><label>결정 내용<textarea disabled={disabled} value={d.value} onChange={e=>onChange({...value,decisions:value.decisions!.map((v,j)=>j===i?{...v,value:e.target.value}:v)})}/></label>{d.evidence&&<small>근거: {d.evidence}</small>}{!disabled&&<button className="button ghost" type="button" onClick={()=>onChange({...value,decisions:value.decisions!.filter((_,j)=>j!==i)})}>후보 제거</button>}</article>)}{!disabled&&<button className="button soft" type="button" onClick={()=>onChange({...value,decisions:[...(value.decisions||[]),{topic:"",value:""}]})}>결정 후보 추가</button>}{onConfirmDecisions&&!!value.decisions?.length&&<button className="button primary" type="button" onClick={onConfirmDecisions}>검토한 결정 확정</button>}
 <h3>업무 후보</h3>{(value.action_items||[]).map((a,i)=><article className="workflow-entry" key={i}><label>업무 내용<input disabled={disabled} value={a.task} onChange={e=>onChange({...value,action_items:value.action_items!.map((v,j)=>j===i?{...v,task:e.target.value}:v)})}/></label><div className="form-grid"><label>담당자 후보<input disabled={disabled} value={a.assignee||""} onChange={e=>onChange({...value,action_items:value.action_items!.map((v,j)=>j===i?{...v,assignee:e.target.value}:v)})}/></label><label>기한 후보<input disabled={disabled} type="date" value={a.due_date||""} onChange={e=>onChange({...value,action_items:value.action_items!.map((v,j)=>j===i?{...v,due_date:e.target.value}:v)})}/></label></div>{a.evidence&&<small>근거: {a.evidence}</small>}{!disabled&&<button className="button ghost" type="button" onClick={()=>onChange({...value,action_items:value.action_items!.filter((_,j)=>j!==i)})}>후보 제거</button>}{onChooseTask&&<button className="button soft" type="button" onClick={()=>onChooseTask(a.task,a.due_date||"")}>이 후보를 배정</button>}</article>)}{!disabled&&<button className="button soft" type="button" onClick={()=>onChange({...value,action_items:[...(value.action_items||[]),{task:"",priority:"medium"}]})}>업무 후보 추가</button>}
 <label>다음 회의 후속 주제<textarea disabled={disabled} value={(value.follow_up_topics||[]).join("\n")} onChange={e=>onChange({...value,follow_up_topics:e.target.value.split("\n")})}/></label></section>;
}
