import { ArrowLeft, ArrowRight, Edit3, ExternalLink, MoreHorizontal, Plus, Sparkles, Trash2, Users } from "lucide-react";
import { Fragment, useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "./api";
import MarkdownContent from "./MarkdownContent";
import type { ActionItem, Decision, EntityType, Meeting, Project } from "./types";

interface Common { projects:Project[]; meetings:Meeting[]; actions:ActionItem[]; decisions:Decision[]; onEdit:(type:EntityType,id:number)=>void; onDelete:(type:EntityType,id:number)=>void; onNotion:(id:number)=>void; onReview:(id:number)=>void; reviewingId:number|null; onSummarize:(id:number)=>void; summarizingId:number|null; onOpenProject:(id:number)=>void; onOpenMeeting:(id:number)=>void; onOpenAction:(id:number)=>void; onOpenDecision:(id:number)=>void; onCreateAction:(projectId:number,meetingId?:number)=>void; }
const projectName=(projects:Project[],id:number)=>projects.find(value=>value.id===id)?.name||"프로젝트 없음";
const date=(value:string|null)=>value?new Intl.DateTimeFormat("ko-KR",{month:"short",day:"numeric"}).format(new Date(`${value.slice(0,10)}T00:00:00`)):"미정";
const Badge=({value}:{value:string})=><span className={`badge ${value.toLowerCase()}`}>{({todo:"할 일",in_progress:"진행 중",done:"완료",cancelled:"취소",low:"낮음",medium:"보통",high:"높음",draft:"초안",confirmed:"확정",SYNCED:"동기화 완료"} as Record<string,string>)[value]||value}</span>;
const RowActions=({type,id,onEdit,onDelete}:{type:EntityType;id:number;onEdit:Common["onEdit"];onDelete:Common["onDelete"]})=><div className="row-actions"><button onClick={()=>onEdit(type,id)} title="수정"><Edit3/></button><button className="danger" onClick={()=>onDelete(type,id)} title="삭제"><Trash2/></button></div>;

export function DashboardPage(props:Common) {
  const open=props.actions.filter(item=>!["done","cancelled"].includes(item.status)); const risk=open.filter(item=>item.risk_level==="high");
  return <div className="page"><div className="metric-grid">{[["프로젝트",props.projects.length,"진행 중인 업무 공간"],["회의",props.meetings.length,"누적 회의 기록"],["미완료 업무",open.length,"확인이 필요한 항목"],["고위험 업무",risk.length,"우선 조치 권장"]].map(item=><article className="metric" key={item[0]}><span>{item[0]}</span><strong>{item[1]}</strong><small>{item[2]}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><PanelTitle kicker="MEETINGS" title="최근 회의"/><MeetingRows {...props} rows={props.meetings.slice(0,5)}/></section><section className="panel"><PanelTitle kicker="RISK WATCH" title="주의할 업무"/><div className="plain-list">{risk.length?risk.slice(0,5).map(item=><button className="dashboard-link" key={item.id} onClick={()=>props.onOpenAction(item.id)}><div><b>{item.task}</b><small>{projectName(props.projects,item.project_id)} · {item.assignee||"미지정"}</small></div><Badge value={item.risk_level}/></button>):<Empty text="주의할 업무가 없습니다."/>}</div></section></div><section className="panel"><PanelTitle kicker="LATEST" title="최근 결정사항"/><DecisionCards {...props} rows={props.decisions.slice(0,3)}/></section></div>;
}
export function ProjectsPage(props:Common) { return <div className="page card-grid">{props.projects.map(project=><article className="entity-card project-card" key={project.id}><div className="card-top"><span className="kicker">PROJECT {project.id}</span><RowActions type="projects" id={project.id} {...props}/></div><h3>{project.name}</h3><p>{project.description||"설명이 없습니다."}</p><footer><span>회의 {props.meetings.filter(m=>m.project_id===project.id).length} · 미완료 {props.actions.filter(a=>a.project_id===project.id&&!['done','cancelled'].includes(a.status)).length}</span><button className="open-project" onClick={()=>props.onOpenProject(project.id)}>프로젝트 열기<ArrowRight/></button></footer></article>)}</div>; }

export function ProjectDetailPage({project,target,onBack,...props}:Common&{project:Project;target?:{meetingId?:number;actionId?:number;decisionId?:number};onBack:()=>void}) {
  const meetings=props.meetings.filter(meeting=>meeting.project_id===project.id);
  const actions=props.actions.filter(action=>action.project_id===project.id);
  const decisions=props.decisions.filter(decision=>decision.project_id===project.id);
  const details=useQuery({queryKey:["project-meeting-details",project.id,meetings.map(value=>value.updated_at)],queryFn:()=>Promise.all(meetings.map(meeting=>api<Meeting>(`/meetings/${meeting.id}`)))});
  const [expanded,setExpanded]=useState<number|null>(target?.meetingId||meetings[0]?.id||null);
  useEffect(()=>{if(target?.meetingId)setExpanded(target.meetingId);const id=target?.actionId?`action-${target.actionId}`:target?.decisionId?`decision-${target.decisionId}`:target?.meetingId?`meeting-${target.meetingId}`:null;if(id)window.setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"center"}),120);},[target?.meetingId,target?.actionId,target?.decisionId]);
  return <div className="page project-detail">
    <button className="back-link" onClick={onBack}><ArrowLeft/>프로젝트 목록</button>
    <section className="project-heading"><div><span className="kicker">PROJECT WORKSPACE</span><h2>{project.name}</h2><p>{project.description||"설명이 없습니다."}</p></div><button className="button primary" onClick={()=>props.onCreateAction(project.id)}><Plus/>Action Item</button></section>
    <div className="project-metrics"><div><strong>{meetings.length}</strong><span>회의</span></div><div><strong>{actions.filter(item=>!["done","cancelled"].includes(item.status)).length}</strong><span>진행 업무</span></div><div><strong>{decisions.filter(item=>item.status==="confirmed").length}</strong><span>확정 결정</span></div></div>
    <ActivityHeatmap meetings={meetings} actions={actions} decisions={decisions}/>
    <div className="project-workspace"><section className="project-meetings"><div className="section-heading"><div><span className="kicker">MEETING RECORDS</span><h3>일자별 회의 기록</h3></div></div>{meetings.length?meetings.map((meeting,index)=>{const detail=details.data?.find(value=>value.id===meeting.id);const related=actions.filter(item=>item.meeting_id===meeting.id);const meetingDecisions=decisions.filter(item=>item.meeting_id===meeting.id);const open=expanded===meeting.id;const newDate=index===0||meetings[index-1].meeting_date!==meeting.meeting_date;const summary=detail?.summary?[`## 회의 요약\n${detail.summary}`,detail.discussion,detail.undecided_topics.length?`## 미결 사항\n${detail.undecided_topics.map(value=>`- ${value}`).join("\n")}`:""].filter(Boolean).join("\n\n"):"";return <Fragment key={meeting.id}>{newDate&&<div className="date-divider">{new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(new Date(`${meeting.meeting_date.slice(0,10)}T00:00:00`))}</div>}<article id={`meeting-${meeting.id}`} className={`meeting-detail ${open?"open":""} ${target?.meetingId===meeting.id?"focused":""}`}><button className="meeting-summary" onClick={()=>setExpanded(open?null:meeting.id)}><div><b>{meeting.title}</b><span><Users/>{meeting.participants.length}명</span></div><span>{related.length}개 업무</span></button>{open&&<div className="meeting-content"><div className="meeting-command"><button className="button soft" disabled={props.summarizingId===meeting.id} onClick={()=>props.onSummarize(meeting.id)}><Sparkles/>{props.summarizingId===meeting.id?"쟁점 분석 중":"AI 쟁점 요약"}</button><button className="button soft" onClick={()=>props.onReview(meeting.id)}><Sparkles/>AI 결정 검토</button><button className="button ghost" onClick={()=>props.onCreateAction(project.id,meeting.id)}><Plus/>Action Item 추가</button></div>{summary&&<div className="record-block summary-block"><h4>쟁점 중심 요약</h4><MarkdownContent content={summary}/></div>}<div className="record-block"><h4>회의 원문</h4>{details.isLoading?<p>회의 내용을 불러오는 중...</p>:<MarkdownContent content={detail?.transcript||"*등록된 회의 원문이 없습니다.*"}/>}</div>{meetingDecisions.length>0&&<div className="record-block"><h4>확정된 결정</h4>{meetingDecisions.map(item=><div id={`decision-${item.id}`} className={`linked-row ${target?.decisionId===item.id?"focused":""}`} key={item.id}><b>{item.topic}</b><span>{item.value}</span></div>)}</div>}<div className="record-block"><h4>연결된 Action Item</h4>{related.length?related.map(item=><div id={`action-${item.id}`} className={`linked-row ${target?.actionId===item.id?"focused":""}`} key={item.id}><div><b>{item.task}</b><span>{item.assignee||"담당자 미지정"} · {date(item.due_date)}</span></div><Badge value={item.status}/></div>):<div className="inline-empty">이 회의에서 생성된 업무가 없습니다.</div>}</div></div>}</article></Fragment>}):<Empty text="이 프로젝트에 등록된 회의가 없습니다."/>}</section>
      <aside className="project-side"><section className="project-actions"><div className="section-heading"><span className="kicker">ACTION BOARD</span><h3>전체 Action Item</h3></div>{actions.length?actions.map(item=><button id={item.meeting_id?`action-side-${item.id}`:`action-${item.id}`} className={`action-compact ${target?.actionId===item.id?"focused":""}`} key={item.id} onClick={()=>item.meeting_id&&setExpanded(item.meeting_id)}><div><b>{item.task}</b><span>{item.assignee||"미지정"} · {date(item.due_date)}</span></div><Badge value={item.status}/></button>):<Empty text="등록된 업무가 없습니다."/>}</section><section className="project-actions project-decisions"><div className="section-heading"><span className="kicker">DECISIONS</span><h3>최근 결정사항</h3></div>{decisions.length?decisions.map(item=><button id={item.meeting_id?`decision-side-${item.id}`:`decision-${item.id}`} className={`action-compact ${target?.decisionId===item.id?"focused":""}`} key={item.id} onClick={()=>item.meeting_id&&setExpanded(item.meeting_id)}><div><b>{item.topic}</b><span>{item.value}</span></div><Badge value={item.status}/></button>):<Empty text="등록된 결정이 없습니다."/>}</section></aside></div>
  </div>;
}

function ActivityHeatmap({meetings,actions,decisions}:{meetings:Meeting[];actions:ActionItem[];decisions:Decision[]}) {
  const today=new Date(); today.setHours(0,0,0,0);
  const start=new Date(today); start.setDate(today.getDate()-84-today.getDay());
  const counts=new Map<string,number>();
  const add=(value:string,weight=1)=>{const key=value.slice(0,10);counts.set(key,(counts.get(key)||0)+weight);};
  meetings.forEach(item=>add(item.meeting_date,2)); actions.forEach(item=>add(item.created_at)); decisions.forEach(item=>add(item.created_at));
  const days=Array.from({length:91},(_,index)=>{const value=new Date(start);value.setDate(start.getDate()+index);const key=value.toISOString().slice(0,10);return {key,value,count:counts.get(key)||0};});
  const total=days.reduce((sum,item)=>sum+item.count,0);
  const months=days.filter((item,index)=>index%7===0).map(item=>item.value.toLocaleDateString("ko-KR",{month:"short"}));
  const level=(count:number)=>count===0?0:count<2?1:count<4?2:count<6?3:4;
  return <section className="activity-panel"><header><div><span className="kicker">PROJECT ACTIVITY</span><h3>최근 13주 활동</h3></div><strong>{total}건</strong></header><div className="heatmap-scroll"><div className="month-row">{months.map((month,index)=><span key={`${month}-${index}`}>{month}</span>)}</div><div className="heatmap-grid">{days.map(item=><span className={`heat-cell level-${level(item.count)}`} key={item.key} title={`${item.key}: 활동 ${item.count}건`}/>)}</div></div><footer><span>회의 2점, 업무·결정 1점 기준</span><div>적음 <i className="heat-cell level-0"/><i className="heat-cell level-1"/><i className="heat-cell level-2"/><i className="heat-cell level-3"/><i className="heat-cell level-4"/> 많음</div></footer></section>;
}

export function MeetingsPage(props:Common) { const [query,setQuery]=useState(""); const [project,setProject]=useState(""); const rows=props.meetings.filter(m=>(!project||m.project_id===Number(project))&&(!query||m.title.toLowerCase().includes(query.toLowerCase()))); return <div className="page"><div className="filters"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="회의 검색"/><select value={project} onChange={e=>setProject(e.target.value)}><option value="">모든 프로젝트</option>{props.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><section className="panel"><MeetingRows {...props} rows={rows}/></section></div>; }

function MeetingRows({rows,...props}:Common&{rows:Meeting[]}) { return <div className="meeting-list">{rows.length?rows.map(meeting=><article key={meeting.id}><button className="record-link" onClick={()=>props.onOpenMeeting(meeting.id)}><b>{meeting.title}</b><small>{projectName(props.projects,meeting.project_id)} · {meeting.participants.join(", ")||"참석자 없음"}</small></button><time>{date(meeting.meeting_date)}</time><div className="meeting-tools"><button className="ai-review" disabled={props.reviewingId===meeting.id} onClick={()=>props.onReview(meeting.id)}><Sparkles/>{props.reviewingId===meeting.id?"분석 중":"AI 결정 검토"}</button><button className={`notion ${meeting.notion_sync_status==="SYNCED"?"synced":""}`} onClick={()=>props.onNotion(meeting.id)}>{meeting.notion_sync_status==="SYNCED"?"Notion 완료":"Notion 전송"}<ExternalLink/></button></div><RowActions type="meetings" id={meeting.id} {...props}/></article>):<Empty text="등록된 회의가 없습니다."/>}</div>; }

export function ActionsPage(props:Common) { const [status,setStatus]=useState(""); const rows=props.actions.filter(item=>!status||item.status===status); return <div className="page"><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">모든 상태</option><option value="todo">할 일</option><option value="in_progress">진행 중</option><option value="done">완료</option></select></div><section className="panel table-panel"><table><thead><tr><th>업무</th><th>프로젝트</th><th>담당자</th><th>기한</th><th>상태</th><th>위험</th><th><MoreHorizontal/></th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td>{item.task}</td><td>{projectName(props.projects,item.project_id)}</td><td>{item.assignee||"-"}</td><td>{date(item.due_date)}</td><td><Badge value={item.status}/></td><td><Badge value={item.risk_level}/> <small>{item.risk_score}</small></td><td><RowActions type="actions" id={item.id} {...props}/></td></tr>)}</tbody></table></section></div>; }

export function DecisionsPage(props:Common) { const [project,setProject]=useState(""); const rows=props.decisions.filter(item=>!project||item.project_id===Number(project)); return <div className="page"><div className="filters"><select value={project} onChange={e=>setProject(e.target.value)}><option value="">모든 프로젝트</option>{props.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><DecisionCards {...props} rows={rows}/></div>; }
function DecisionCards({rows,...props}:Common&{rows:Decision[]}) { return <div className="decision-grid">{rows.length?rows.map(item=><article className="entity-card" key={item.id}><div className="card-top"><span className="kicker">{projectName(props.projects,item.project_id)}</span><RowActions type="decisions" id={item.id} {...props}/></div><button className="decision-link" onClick={()=>props.onOpenDecision(item.id)}><h3>{item.topic}</h3><p>{item.value}</p></button><footer><Badge value={item.status}/><span>{date(item.updated_at)}</span></footer></article>):<Empty text="등록된 결정사항이 없습니다."/>}</div>; }
function PanelTitle({kicker,title}:{kicker:string;title:string}) { return <header className="panel-title"><span className="kicker">{kicker}</span><h2>{title}</h2></header>; }
function Empty({text}:{text:string}) { return <div className="empty">{text}</div>; }
